/*
 * Traffic Lights
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ControlTrafficLights400Response
 */
public class ControlTrafficLights400ResponseTest {
    private final ControlTrafficLights400Response model = new ControlTrafficLights400Response();

    /**
     * Model tests for ControlTrafficLights400Response
     */
    @Test
    public void testControlTrafficLights400Response() {
        // TODO: test ControlTrafficLights400Response
    }

    /**
     * Test the property 'errormsg'
     */
    @Test
    public void errormsgTest() {
        // TODO: test errormsg
    }

    /**
     * Test the property 'success'
     */
    @Test
    public void successTest() {
        // TODO: test success
    }

}
