/*
 * Traffic Lights
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for GetAllScheduledTrafficLightsEvents200Response
 */
public class GetAllScheduledTrafficLightsEvents200ResponseTest {
    private final GetAllScheduledTrafficLightsEvents200Response model = new GetAllScheduledTrafficLightsEvents200Response();

    /**
     * Model tests for GetAllScheduledTrafficLightsEvents200Response
     */
    @Test
    public void testGetAllScheduledTrafficLightsEvents200Response() {
        // TODO: test GetAllScheduledTrafficLightsEvents200Response
    }

    /**
     * Test the property 'color'
     */
    @Test
    public void colorTest() {
        // TODO: test color
    }

    /**
     * Test the property 'day'
     */
    @Test
    public void dayTest() {
        // TODO: test day
    }

    /**
     * Test the property 'hours'
     */
    @Test
    public void hoursTest() {
        // TODO: test hours
    }

    /**
     * Test the property 'minutes'
     */
    @Test
    public void minutesTest() {
        // TODO: test minutes
    }

    /**
     * Test the property 'month'
     */
    @Test
    public void monthTest() {
        // TODO: test month
    }

    /**
     * Test the property 'seconds'
     */
    @Test
    public void secondsTest() {
        // TODO: test seconds
    }

    /**
     * Test the property 'street'
     */
    @Test
    public void streetTest() {
        // TODO: test street
    }

    /**
     * Test the property 'year'
     */
    @Test
    public void yearTest() {
        // TODO: test year
    }

}
