/*
 * Traffic Lights
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * LoginUser401Response
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-11-23T10:39:51.004504690+01:00[Europe/Berlin]")
public class LoginUser401Response {
  public static final String SERIALIZED_NAME_ERRORMSG = "errormsg";
  @SerializedName(SERIALIZED_NAME_ERRORMSG)
  private String errormsg;

  public static final String SERIALIZED_NAME_SUCCESS = "success";
  @SerializedName(SERIALIZED_NAME_SUCCESS)
  private Boolean success;

  public LoginUser401Response() {
  }

  public LoginUser401Response errormsg(String errormsg) {
    
    this.errormsg = errormsg;
    return this;
  }

   /**
   * Error message.
   * @return errormsg
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Error message.")

  public String getErrormsg() {
    return errormsg;
  }


  public void setErrormsg(String errormsg) {
    this.errormsg = errormsg;
  }


  public LoginUser401Response success(Boolean success) {
    
    this.success = success;
    return this;
  }

   /**
   * success indicates if login worked.
   * @return success
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "success indicates if login worked.")

  public Boolean getSuccess() {
    return success;
  }


  public void setSuccess(Boolean success) {
    this.success = success;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoginUser401Response loginUser401Response = (LoginUser401Response) o;
    return Objects.equals(this.errormsg, loginUser401Response.errormsg) &&
        Objects.equals(this.success, loginUser401Response.success);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errormsg, success);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoginUser401Response {\n");
    sb.append("    errormsg: ").append(toIndentedString(errormsg)).append("\n");
    sb.append("    success: ").append(toIndentedString(success)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("errormsg");
    openapiFields.add("success");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to LoginUser401Response
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!LoginUser401Response.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in LoginUser401Response is not found in the empty JSON string", LoginUser401Response.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!LoginUser401Response.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `LoginUser401Response` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if ((jsonObj.get("errormsg") != null && !jsonObj.get("errormsg").isJsonNull()) && !jsonObj.get("errormsg").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `errormsg` to be a primitive type in the JSON string but got `%s`", jsonObj.get("errormsg").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!LoginUser401Response.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'LoginUser401Response' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<LoginUser401Response> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(LoginUser401Response.class));

       return (TypeAdapter<T>) new TypeAdapter<LoginUser401Response>() {
           @Override
           public void write(JsonWriter out, LoginUser401Response value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public LoginUser401Response read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of LoginUser401Response given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of LoginUser401Response
  * @throws IOException if the JSON string is invalid with respect to LoginUser401Response
  */
  public static LoginUser401Response fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, LoginUser401Response.class);
  }

 /**
  * Convert an instance of LoginUser401Response to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

